#!/bin/bash

# Name:
# Date:
# Class:
# Lab:

# This script does . . .

 

# First, if the user needs to be root, check to make sure the root user is executing this command. If not, then inform the user they must use root privileges

 

# Then, appropriate comments for whatever this script does.

 

# Exit status
